services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /home/ochir/projects_1/online-shop/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ochir/projects_1/online-shop:/var/www/html

  php-fpm:
    build: ./docker/php
    volumes:
      - /var/www/html:/var/www/html

  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}